name: Haskell CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.6.3' # or specify a version like '8.10.7'
        cabal-version: 'latest' # or specify a version like '3.4'

    - name: Clean
      run: cabal clean

    - name: Build
      run: cabal build all

    - name: Test
      run: cabal test all 